<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="EL1809" Id="{2d9d8afb-39a4-4fda-a15a-2bc58d6817d2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1809
VAR
	DI_ESR1_tmp : DIChannel;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EL1809">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>